"""mqtt_relay constants."""

APP_NAME = "mqtt_relay"
VERSION = "0.1.0"

DEF_MSG_TIMEOUT = 5  ## TODO

## Argument defaults
DEF_MQTT_HOST = "localhost"
DEF_MQTT_PORT = 1883
DEF_MQTT_PORT_TLS = 8883
DEF_CONNECT_TIMEOUT = 10
DEF_INOTIFY_TRIGGER_DELAY = 0
DEF_INOTIFY_RESTART_DELAY = 2
DEF_DEBUG_LEVEL = 0
